### ISSUE TITLE
Spelling error in description

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/podman-desktop-redhat-account-ext#180]
![Screenshot 2024-07-11 at 10 40 35 AM](https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/6422176/c2b47ee5-9f57-4011-9b75-3c5a14540de6)

Accoint -> Account

I'm unable to edit the description! Thought to let you know.

**Comment by dgolovin** [comment]
Updated.
Closing the issue.
