### ISSUE TITLE
Light Mode: The field on Authentication Page with a name and logout button is dark on Light Mode on

### ISSUE THREAD

**Issue by odockal** [redhat-developer/podman-desktop-redhat-account-ext#231]
![Screenshot_20240808_185002](https://github.com/user-attachments/assets/69f33b2d-021c-4121-8a02-d3f9a9d66d38)

**Comment by dgolovin** [comment]
Fixed yesterday. It was podman issue, because extension does not control UI styles. 

https://github.com/containers/podman-desktop/pull/8380
