### ISSUE TITLE
Building a rhel toolbox image from guide/readme is broken

### ISSUE THREAD

**Issue by odockal** [redhat-developer/podman-desktop-redhat-account-ext#233]
I was trying to build an image using containerfile mentioned in README.

I got: `.../build/oolbox.containerfile: no such file or directory` during the build. It seems that building the image is missing a letter. Not sure if podman-desktop or sso problem.

![Screenshot_20240809_173829](https://github.com/user-attachments/assets/b2408194-f8c3-4644-b090-dd23e6855ea3)

**Comment by odockal** [comment]
The problem seems to be on podman-desktop side. This happens when I use different context folder for the build other then where is containerfile.

**Comment by dgolovin** [comment]
Work for me on latest main build in dev environment. I am using simple Container file with `FROM --platform=linux/amd64 registry.redhat.io/ubi8/toolbox`.It also works for RHEL8 [registry.redhat.io/rhel8/toolbox](http://registry.redhat.io/rhel8/toolbox)

![image](https://github.com/user-attachments/assets/d018efa4-07cb-47b0-8260-cbff5d00f3b1)

**Comment by dgolovin** [comment]
rhel9 image works too.

**Comment by odockal** [comment]
@dgolovin It is not about the image, as I first assumed, it is about using different context build folder. Can you please try that? And, it is not on sso side, after all.

**Comment by dgolovin** [comment]
@odockal I have the same error if I use context folder the same way. Could someone transfer the issue to podamn-desktop repo. It has nothing to do with this extension.

**Comment by jeffmaury** [comment]
> @odockal I have the same error if I use context folder the same way. Could someone transfer the issue to podamn-desktop repo? It has nothing to do with this extension.

Can't transfer between GH orgs. Need to be cloned then closed

**Comment by odockal** [comment]
Cloned on podman-desktop side: https://github.com/containers/podman-desktop/issues/8460
