### ISSUE TITLE
e2e tests are broken for pr-check, nightly and e2e-test-main

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/podman-desktop-redhat-account-ext#288]
See 
* https://github.com/redhat-developer/podman-desktop-redhat-account-ext/actions/workflows/e2e-main.yaml
* https://github.com/redhat-developer/podman-desktop-redhat-account-ext/actions/workflows/sso-e2e-nightly-windows.yaml
* https://github.com/redhat-developer/podman-desktop-redhat-account-ext/actions/workflows/pr-check.yaml

**Comment by odockal** [comment]
There were changes in the upstream (podman-desktop/tests) that broken the builds. I will update the tests according to new api.
