### ISSUE TITLE
Use protocol handler to redirect to Podman Desktop window after authentication

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/podman-desktop-redhat-account-ext#29]
There are two options:
1. Register podman-desktop://uri for podman-desktop SSO client and that means SSO page will redirect to podman desktop page that should handle SSO token extraction the same way local web server does in authentication provider implementation
2. Add button `Return to Podman Desktop` on the page showed in browser after successful authentication

**Comment by slemeur** [comment]
The flow should be automated - there should not be a need for the end-user to click on a button "return to podman desktop"

**Comment by slemeur** [comment]
closing in favor of https://github.com/redhat-developer/podman-desktop-redhat-account-ext/issues/40
