### ISSUE TITLE
Package subscription management and container registry authorizer API clients as libraries

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/podman-desktop-redhat-account-ext#31]
Two generated clients should be part of mono repository under @redhat-developer organization 

https://github.com/redhat-developer/redhat-javascript-rest-api-clients

Packages should be in repository's packages folder: 
* Red Hat Subscription Manager 
* Red Hat Container Registry Authorizer

**Comment by slemeur** [comment]
@dgolovin : I see this moved from "in review" to "done" state. What's the status and eventually associated PR.
cc @jeffmaury

**Comment by jeffmaury** [comment]
Repository has been created and published on NPM: https://github.com/redhat-developer/redhat-javascript-rest-api-clients
