### ISSUE TITLE
Add a sign in button to replace drop-down menu

### ISSUE THREAD

**Issue by vrothberg** [redhat-developer/podman-desktop-redhat-account-ext#37]
It currently takes 2 mouse clicks to sign in. Can we move the drop down menu into a button instead to optimize for our clicks/keystrokes metric?

![Screenshot 2024-02-13 at 13 35 30](https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/11679875/c121fef5-d22a-4f0a-9c11-4e0f3038fa62)

There is a logout button displayed once logged in. So it doesn't feel symmetric.
![Screenshot 2024-02-13 at 13 37 39](https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/11679875/f1dd6f68-d1d3-46ca-94a6-8682e9d472d8)

Ignore until https://github.com/redhat-developer/podman-desktop-redhat-account-ext/pull/35 has merged.

Cc: @dgolovin @benoitf @jeffmaury @slemeur

**Comment by benoitf** [comment]
@vrothberg if you could file this issue on Podman Desktop side as this extension won't be able to change stuff

**Comment by vrothberg** [comment]
Will do, thanks!

**Comment by vrothberg** [comment]
Closing in favor of https://github.com/containers/podman-desktop/issues/5979

**Comment by slemeur** [comment]
Reopen, so we can track the dependency from the extension stand point.

**Comment by vrothberg** [comment]
Being worked on in https://github.com/containers/podman-desktop/pull/6446

**Comment by dgolovin** [comment]
https://github.com/containers/podman-desktop/pull/6446 resolved. Closing.

**Comment by vrothberg** [comment]
Great work, thank you!
