### ISSUE TITLE
Add logo for Red Hat Registry

### ISSUE THREAD

**Issue by vrothberg** [redhat-developer/podman-desktop-redhat-account-ext#38]
I'd love to see the Red Hat logo in the Registries menu after a successful login.  As shown below, there is a visual difference between the preset registries and the one added by the extension.  I'd like to fill this gap.

I am also looking into figuring out an alternative name to replace the URL `registry.redhat.io` with a more human-friendly name.

![Screenshot 2024-02-13 at 13 46 12](https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/11679875/3ac37d04-35ae-4329-8293-a820b6844ad1)

Ignore until https://github.com/redhat-developer/podman-desktop-redhat-account-ext/pull/35 has merged.

Cc: @dgolovin @benoitf @jeffmaury @slemeur

**Comment by benoitf** [comment]
I would just avoid to make this extension bigger and bigger and keep a separation of concerns. 

IMHO this extension should only manage the authentication and delegate/require to other extensions

For example stuff for registries ==> redhat registry extension

or this extension is no longer fitting in a pure 'identity provider' and more a 'all-in-one'


- we should be able to update logos or add new Red Hat registries, etc without needing to release a new version of the redhat-account extension

**Comment by deboer-tim** [comment]
I guess I was thinking of this as a 'RH accounts' extension. I'm ok moving to another podman-desktop-redhat-* extension, which would need to depend on this one so you can actually login to the registry.

**Comment by dgolovin** [comment]
BTW icon and name for the registry does not survive podman desktop restart (see https://github.com/containers/podman-desktop/issues/6218)
