### ISSUE TITLE
Authentication state is showing "logged out" after restart of Podman Desktop

### ISSUE THREAD

**Issue by vrothberg** [redhat-developer/podman-desktop-redhat-account-ext#39]
The extension claims to be logged out after a restart.  I'd love us to find a way to improve on that.  There may be ways to store/cache the refresh token or to check whether we're logged into `registry.redhat.io` and do a status check of subscription-manager inside the VM.  There may be other options as well.

![Screenshot 2024-02-13 at 13 50 30](https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/11679875/dd53c33f-7a35-4f41-aca1-01dcf73adfde)

Ignore until https://github.com/redhat-developer/podman-desktop-redhat-account-ext/pull/35 has merged.

depends on https://github.com/containers/podman-desktop/issues/6044.

Cc: @dgolovin @benoitf @jeffmaury @slemeur

**Comment by odockal** [comment]
This issue also introduces another unwanted behavior. If I am successfully logged into registry.redhat.io after first authentication using SSO (which is expected?), I am not logged out of if I "sign off" from the SSO. I am still logged into registry. 
After application restart, I am still logged into registry, but I logged off from the SSO (no matter if I wanted or not) -> I log into SSO again, but this time new registry record appears. 

![Screenshot_20240301_175022](https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/19164299/c9625b92-5bdd-494a-8f8d-f1f890ee4a96)

**Comment by vrothberg** [comment]
@dgolovin is the secure-storage feature tracked somewhere in Podman Desktop? Can we link it here?

**Comment by benoitf** [comment]
secure storage has been implemented there https://github.com/containers/podman-desktop/pull/6422 and provided to extensions there https://github.com/containers/podman-desktop/pull/6423 so I think @dgolovin now you can store the token there

**Comment by vrothberg** [comment]
Thanks, @benoitf !  We're getting really close :)
