### ISSUE TITLE
Avoid the success page and automatically redirect the user in Podman Desktop

### ISSUE THREAD

**Issue by vrothberg** [redhat-developer/podman-desktop-redhat-account-ext#40]
Is possible to automatically close the [sso.redhat.com](http://sso.redhat.com/) page and get redirected to Podman Desktop?
Or is the www/success.html page mandatory?

My main intention is to reduce the amount of mouse clicks and keystrokes.  In this case, we need 1 click to close the tab followed by one or more clicks or keystrokes to refocus on Podman Desktop.

![Screenshot 2024-02-13 at 13 58 48](https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/11679875/4cf78806-5648-46cf-8e7e-50bf4f133696)

Ignore until https://github.com/redhat-developer/podman-desktop-redhat-account-ext/pull/35 has merged.

Cc: @dgolovin @benoitf @jeffmaury @slemeur @deboer-tim

**Comment by dgolovin** [comment]
we can redirect to podman-desktop:// url after successful login on page loaded event as a first iteration.

**Comment by vrothberg** [comment]
Sounds great!

**Comment by slemeur** [comment]
Duplicates https://github.com/redhat-developer/podman-desktop-redhat-account-ext/issues/29

**Comment by jeffmaury** [comment]
> The idea suggested by @benoitf would be ideal:
> 
> > if it displays the success page, then here I think slack is doing that, the success page can add a open app/ link redirect to podman-desktop://
> > and we could here close the success window (either like a timeout close) or be smarter (it would require some enhancements in Podman Desktop etc but for example if success.html open podman-desktop://extension/redhat.sso then we can notify the extension that could modify something pulled by the success.html page that will close the page in case of a successful redirect

The OpenID client that Podman Desktop uses gets redirected to a local http server that is being created by Podman Desktop so it knows when the handshake is finished and could request focus for Podman Desktop
