### ISSUE TITLE
Properly handle "sign out" flow and cleanup all added resources/sessions

### ISSUE THREAD

**Issue by vrothberg** [redhat-developer/podman-desktop-redhat-account-ext#41]
When logging out of the Red Hat account, I currently cannot observe an action to be taken.  I think we should consider logging out of `registry.redhat.io` and also unregister subscription-manager in the VM?  That would feel symmetric to what happens when logging in.

![Screenshot 2024-02-13 at 14 29 05](https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/11679875/3af9cd9a-034d-474c-be1d-4878fee9b24f)

**Comment by dgolovin** [comment]
Right now it is just removing session from provider internal in memory storage. User is still logged in in browser.

**Comment by slemeur** [comment]
> Right now it is just removing session from provider internal in memory storage. User is still logged in in browser.
Then this is not correct as we are not cleaning up the things properly.

It must handle the complete cleanup, imagine a case where the user has 2 accounts and wants to switch from one to another. 

Complete cleanup:
- the user should not be able to pull from registry.redhat.io from podman desktop or podman
- the browser session must be cleaned
- the subscription info in the podman machine must be removed
