### ISSUE TITLE
Linux support or warning regarding functionality

### ISSUE THREAD

**Issue by mrguitar** [redhat-developer/podman-desktop-redhat-account-ext#42]
So part of the plugin functions on Fedora. :)  I understand that's not the priority or goal right now, which is fine. 

Longer term, it would be ideal if the plug-in can notify the user that it's intended for use on Mac/Windows system w/ a podman machine. 

Even better would be to make this work on a Linux system and injecting certs on the host (or whatever) and pass them into containers.  Not a big priority at the moment, but I'm opening this issue as I suspect others will run into this.

**Comment by dgolovin** [comment]
@mrguitar this is RH SSO Integration extension. It let you login to your Red Hat SSO account, get the access token and then you can communicate with various Red Had APIs like:
* Openshif Sandbox registration service
* Red Hat Subscriptions API
* etc

The extension is not working directly with containers. IMO [Podman Desktop repository](https://github.com/containers/podman-desktop) is a better place for such request.

**Comment by vrothberg** [comment]
I assume the request is to not only support a running podman-machine VM but also support running/using the Linux host directly?

**Comment by mrguitar** [comment]
@dgolovin, I'm aware of the use case for this plug-in, and it half worked on one of my Fedora boxes. I was forwarded to the SSO page, I logged in, and the UI showed my redhat account as authenticated. ...but that was as far as I could get. I should note that I didn't expect this to work as podman desktop on Fedora uses the host directly instead of using a podman machine (please correct me if this is wrong, but I'm pretty sure it's right). 

Anyway, after authenticating I wasn't able to pull "rhel" images from registry.redhat.io. It's quite possible that I did something wrong and this was user error. Just for fun I put the extension on my other laptop and the three dots at the end of the bar are missing, and I can't click log-in. I don't know if that's intentional or not, but I found that (meaning the missing option to click on) to be a pretty decent compromise if the plugin doesn't function all the way on a fedora box. 

@vrothberg, yes. In a perfect world, it would be awesome to use this on a Linux host. .....but I believe this will require a fiar amount of work and please do not adjust priorities for this. I consider this a "maybe some day" or a "nice to have" considering the PD users base is primarily Windows & Mac. Please let me know my prose need more clarification. Cheers!

**Comment by vrothberg** [comment]
> Just for fun I put the extension on my other laptop and the three dots at the end of the bar are missing, and I can't click log-in.

I guess that means the other laptop has a pre-1.7 version of Podman Desktop.  The latest (unpushed) extension will error out in this case.

Thanks for elaborating, @mrguitar!  Linux is a target as well, so we may need to massage the code a bit.  It should work when you're using a `podman machine` VM on Linux but not when running against the socket on the host.

**Comment by vrothberg** [comment]
Opened https://github.com/redhat-developer/podman-desktop-redhat-account-ext/pull/53.
