### ISSUE TITLE
Send telemetry when creating container image registry service accounts and subscription activation keys

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/podman-desktop-redhat-account-ext#43]
There should be telemetry send after tha API calls to create:
* container registry service account
* subscription activation key

Telemetry data should indicate if the call was successful or failed

Related to #35.

**Comment by dgolovin** [comment]
> this is unclear.

@slemeur What telemetry should be sent from extension then?

**Comment by vrothberg** [comment]
Things we want to know:
- Installation of the extension
- Login and logout
- Errors in the flow (e.g., when service-account creation fails or sub-man fails or logging into the registry, etc.).  Helps us understand _where_ things break and identify those more easily.
