### ISSUE TITLE
Remove copy of podman CLI implementation and migrate to new API when implemented

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/podman-desktop-redhat-account-ext#44]
Current implementation is copied form podman extension and should be removed when podman desktop has new API to call podman commands https://github.com/containers/podman-desktop/issues/5990.

**Comment by dgolovin** [comment]
@benoitf where package with API definition should be placed. Should it be done the same way as for @podman-destop/api.

**Comment by benoitf** [comment]
yes probably we should have it part of the podman extension and published on each release

probably another package or refactor the podman extension to have multiple folders (not sure it'll work fine to automatically load the extension using that way)

**Comment by dgolovin** [comment]
@benoitf Would implementing it as `podman` module in the extension-api similar to [docker.exec](https://docs.docker.com/desktop/extensions-sdk/dev/api/reference/interfaces/Exec/) work? 

Here is an implementation https://github.com/containers/podman-desktop/compare/main...dgolovin:i5990?expand=1

**Comment by benoitf** [comment]
@dgolovin there should be no podman module ( no changes in the extension loader file)

it's the other extensions that can get the extension object from `get extensions(extensionName)` and then use the `.exports` object from there

**Comment by dgolovin** [comment]
> there should be no podman module ( no changes in the extension loader file)

@benoitf I can do it in similar fashion as #7961, but that will:
* produce additional package in packages folder
* package will be published not matter if there is no changes in API
* it still would be used in extension only

For external contributions that would be required, podman extension is built-in and always present why not expose it in @podamn-desktop/api?

**Comment by benoitf** [comment]
because the podman extension might not always be a default extension. Also users can disable the extension.

And it should always be within extensions.
