### ISSUE TITLE
Restore logo for Red Hat Authentication extension on Extensions preference page

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/podman-desktop-redhat-account-ext#48]
Right now default extension logo is shown

![image](https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/620330/7d026f67-8696-4d62-8c06-4e2ad63e9151)

**Comment by vrothberg** [comment]
Strange.  It works for me using the latest main of the extension (d5e55daf7368) and Podman Desktop (9f6ea45859f9).

![Screenshot 2024-02-19 at 13 19 54](https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/11679875/7db908d0-95cb-49cb-aa64-b895f01fbd86)

How did you run/install the extension?

**Comment by vrothberg** [comment]
Tested again.  Works for me on Mac and Linux.

**Comment by slemeur** [comment]
I can reproduce the issue on Mac.
<img width="1078" alt="Screenshot 2024-02-28 at 13 27 28" src="https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/1636769/d86d2bbc-7cc0-498c-b579-85290a45e12c">
