### ISSUE TITLE
Empty page is shown in browser after sucessful authentication

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/podman-desktop-redhat-account-ext#49]
![image](https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/620330/2f8daa59-fa93-4edc-a24c-df9dd9c2be26)

**Comment by slemeur** [comment]
Should be fixed by https://github.com/redhat-developer/podman-desktop-redhat-account-ext/issues/40
