### ISSUE TITLE
Enhance PR check for really checking code

### ISSUE THREAD

**Issue by benoitf** [redhat-developer/podman-desktop-redhat-account-ext#55]
PR check is just building the extension but it does not check that the typescript is valid or run any unit tests or linter, etc so you can easily break anything

**Comment by odockal** [comment]
It would be nice to practically reuse what podman-desktop repo utilize. 
Just hints what to add: sonar, dependabot (I have not really check if it is there?)

**Comment by odockal** [comment]
We should also enable unit tests on PR check and other workflows.
