### ISSUE TITLE
switch from rollup to vite

### ISSUE THREAD

**Issue by benoitf** [redhat-developer/podman-desktop-redhat-account-ext#65]
I think we got issues in the past with rollup (with 3rd party dependencies)

we switched extensions to use vite in Podman Desktop, probably this one should be converted as well.

**Comment by dgolovin** [comment]
Related to #38, due to rollup image plugin not being able to handle image import.

**Comment by dgolovin** [comment]
Tried to switch but whatever I do I always got an error about `window` module resolution and I could not get past it. I am using the same config for vite from other extensions and the extension built with it fails to load after installation.

**Comment by dgolovin** [comment]
After migrating to vite the openid-client prints out message below

```
Error: Algorithm "sha256"  not supported. supported values: sha1, md5, passthrough
console.<computed> @ VM5:2
(anonymous) @ VM5:2
emit @ VM4 sandbox_bundle:2
onMessage @ VM4 sandbox_bundle:2
```

Using suggested plugins to bring back 'sha256' digest did not help. 

I sent PR above, that addresses only build speed issue and leaves rollup intact.
