### ISSUE TITLE
RH registry displayed twice

### ISSUE THREAD

**Issue by vrothberg** [redhat-developer/podman-desktop-redhat-account-ext#70]
When already logged into `registry.redhat.io`, I see two entries after signing into my RH account.

I think we may need to logout before logging into the registry.

![image](https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/11679875/58979ad6-0f26-4f80-b0ca-d5779a3df9e2)

**Comment by dgolovin** [comment]
This is because of https://github.com/containers/podman-desktop/issues/6218

**Comment by odockal** [comment]
Here is video:
![sso-extension-tworegistries](https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/
19164299/209ecdb6-75a7-484d-9e03-29f0fa284016)

**Comment by benoitf** [comment]
commenting here, the extension should register the registry at every startup but using suggest API (so it's adding the entry, no matter if we successfully login or not)
