### ISSUE TITLE
Exploratory Testing of the SSO Extension

### ISSUE THREAD

**Issue by odockal** [redhat-developer/podman-desktop-redhat-account-ext#72]
We will go though the README and look, if we can break something. Try multiple areas of the extension.
* Smoke test scenario -> Step by step of the README in order to make sure users can achieve the goal of the extension, the requested functionality must work
* Extenstion installation -> installation of the extension via OCI image in Podman Desktop, handling the extension in podman desktop (disable -> UI elements check, re-enablement, looking for errors in the dev console)
* reproducing reported issue -> when trying to look at what is reported and was fixed, we can create a regression suite of test cases (manual for start)
* Visual check - verification of the UI elements
* Verification on multiple platforms

**Comment by odockal** [comment]
smoke test scenario:
I managed to get through all of the steps, except, I am not able to subscribe the system of the in the example containerfile.
I am getting: 
```
Uploading the build context from /home/odockal/git/podman-desktop-qe/examples/images...Can take a while...
Building rhel9-toolbox...
STEP 1/2: FROM registry.redhat.io/rhel9/toolbox
Trying to pull registry.redhat.io/rhel9/toolbox:latest...
Getting image source signatures
Checking if image destination supports signatures
Copying blob sha256:cfba5888dd9625c962d3158f6f8e8ea865cb0fdad14722b9521d5e9287577cd6
Copying blob sha256:1bd75c368cb585e77e0b3234a750db4235fa64ff8b5b9ca8da8bf7a34ec9ecaa
Copying config sha256:8c0cf48d63fe99240056c972f949da902c9196cce8da1795abd016154e95a781
Writing manifest to image destination
Storing signatures
STEP 2/2: RUN  dnf install -y kernel
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Red Hat Universal Base Image 9 (RPMs) - BaseOS  1.3 MB/s | 515 kB     00:00    
Red Hat Universal Base Image 9 (RPMs) - AppStre 3.9 MB/s | 1.8 MB     00:00    
Red Hat Universal Base Image 9 (RPMs) - CodeRea 516 kB/s | 192 kB     00:00    
No match for argument: kernel
Error: Unable to find a match: kernel
Error:building at STEP "RUN dnf install -y kernel": while running runtime: exit status 1
```

**Comment by dgolovin** [comment]
I think it is because you don't have Simple Content Access enabled on your account in Customer Portal
![image](https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/620330/0dc97685-bb99-4c1a-b6d7-8ae9bbd61c67)

**Comment by dgolovin** [comment]
It is now enabled by default for new accounts. For old accounts it should be enabled manually. At some point they are going to enable it anyway. We might need to add a check for that too.

**Comment by odockal** [comment]
@dgolovin you are right:
![Screenshot_20240304_151824](https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/19164299/5ad4890a-9eba-4d01-b102-1c4cb93a690c)
Do we need to tackle that for old accounts? At least in a form of a notification or better error message?

**Comment by dgolovin** [comment]
There should be a warning message about that.

**Comment by odockal** [comment]
We have prepared testing tracker to track the testing results for any release starting 0.0.2. Also finished pre-1.0.0 testing. 
Next is to test 1.0.0.
