### ISSUE TITLE
Implement E2E test for extension installation into podman desktop

### ISSUE THREAD

**Issue by odockal** [redhat-developer/podman-desktop-redhat-account-ext#76]
We would like to have a first e2e test that would verify that it is possible to install the extension via OCI image.

**Comment by vrothberg** [comment]
Can you elaborate more?  I don´t understand the exact request/problem.

**Comment by odockal** [comment]
The request aims for an e2e tests that use @podman-desktop/tests-playwright npm package. The test itself installs sso extension via OCI image in Podman Desktop Settings -> Extensions Page.
