### ISSUE TITLE
Sign-in button in status bar

### ISSUE THREAD

**Issue by vrothberg** [redhat-developer/podman-desktop-redhat-account-ext#78]
To better promote the SSO feature and make it more accessible, we talked about adding a button/indicator to the navigation bar at the bottom.

I imagine a button with the Red Hat logo and specific text that on click fires the sign-in process.  It should also indicate whether the user is signed in or not.

![image](https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/11679875/8b0a9f82-d0bf-42fb-8a38-c3a9fe540389)

@slemeur does that reflect what you had in mind?

**Comment by deboer-tim** [comment]
It looks like https://github.com/containers/podman-desktop/issues/6297 was opened to track this.

**Comment by vrothberg** [comment]
Being worked on in https://github.com/containers/podman-desktop/pull/6446

**Comment by dgolovin** [comment]
I have an icon on status bar 

![Image](https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/620330/33aba04f-c96d-4279-b613-441f1614c135)

@benoitf How do I make it red?

**Comment by benoitf** [comment]
It's not possible to pickup colors for status bar elements

It is to avoid Christmas tree effect

**Comment by dgolovin** [comment]
@benoitf  @vrothberg Then we cannot use White Hat with Black stripe icon. It seems according to https://brand.redhat.com it can be: Red/White, Red/black or Black/white only. There is no White/black colored icon.

**Comment by dgolovin** [comment]
We still allow colors on the action bar (openshift icon is red)

![image](https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/620330/44b3a268-cf23-407c-b290-6b7a5d08c01e)

What is there is limited number of colors: red, green and yellow?

**Comment by vrothberg** [comment]
How about displaying a green check mark ✅ next to the logo when being signed in?

**Comment by deboer-tim** [comment]
See previous comment - it's intentionally not possible today. Statusbar is kept to muted colors to avoid distraction (and as a user, I really wouldn't like either of these last two suggestions).

**Comment by dgolovin** [comment]
> See previous comment - it's intentionally not possible today. Statusbar is kept to muted colors to avoid distraction (and as a user, I really wouldn't like either of these last two suggestions).

I am still confused, why text editor colored like Christmas tree is fine, but status bar colored the same way is not ;)

But, I am going to use muted color hat for now.
