### ISSUE TITLE
prompted before getting redirected to Podman Desktop

### ISSUE THREAD

**Issue by vrothberg** [redhat-developer/podman-desktop-redhat-account-ext#89]
I am now seeing a prompt before getting redirected to Podman Desktop.  I am not sure I hit this before.

![Screenshot 2024-03-21 at 08 44 16](https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/11679875/6bd0dfd9-4f27-4789-b7a7-14cedc53eb07)

**Comment by dgolovin** [comment]
@vrothberg yes, it was always this way.
