### ISSUE TITLE
The SSO plugin fails when building images for different architectures

### ISSUE THREAD

**Issue by mrguitar** [redhat-developer/podman-desktop-redhat-account-ext#90]
I'm on a Mac and building for x86 (because the rest of the world live here for now). The developer subscriptions includes access to both aarch64 & x86_64 content, however I believe sub-man is only accessing the native arch content w/ the included entitlement. 

STEP 3/5: RUN dnf install -y cockpit cockpit-podman cockpit-pcp 
Updating Subscription Management repositories.
Unable to read consumer identity
subscription-manager is operating in container mode.

This system is not registered with an entitlement server. You can use subscription-manager to register.

Error: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".
Error:building at STEP "RUN dnf install -y cockpit cockpit-podman cockpit-pcp": while running runtime: exit status 1

![multi-arch](https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/1071620/d24d5dc9-b99e-4349-9ea2-a8356b0ae454)

Everything works as expected when I build the container using native aarch64.

**Comment by vrothberg** [comment]
Thanks for reporting, @mrguitar!  This cross-arch builds aren't supported on RHEL via qemu I guess we're entering new territory running on FCOS.

We need to test this workflow, Cc: @jeffmaury @deboer-tim

**Comment by vrothberg** [comment]
This will be moved into Jira.

**Comment by mohan-shash** [comment]
https://issues.redhat.com/browse/BIFROST-273
