### ISSUE TITLE
create a `custom.facts` file for multi-arch builds

### ISSUE THREAD

**Issue by vrothberg** [redhat-developer/podman-desktop-redhat-account-ext#95]
We need to create `/etc/rhsm/facts/custom.facts` with following content to support multi-arch builds for aarch64 and amd64:
```JSON
{
  "supported_architectures": "aarch64,x86_64"
}
```

**Comment by benoitf** [comment]
should it not be included by the podman 5 machines files ?

**Comment by vrothberg** [comment]
> should it not be included by the podman 5 machines files ?

I think the SSO extension should deal with it for now.  5.0 is already out, so the extension must expect homogeneous machines.

**Comment by m-horky** [comment]
The file can be named as `{{ anything }}.facts`, so I'd recommend it is named as something uniquely identifiable. Like `podman-redhat-extension.facts`, for example, so it is clear why the file is there.

**Comment by vrothberg** [comment]
Thanks for the guidance, @m-horky!  Let's do that.
